services:
  backend:
    build: ./backend
    restart: always

    depends_on:
      - mongodb

    env_file:
      - .env
    secrets:
      - mongo_password

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./frontend

volumes:
  mongo-data:

secrets:
  mongo_password:
    file: ./mongo_password.txt
